### ISSUE TITLE
Cannot run the script - crashes every time before it can output ui.package

### ISSUE THREAD

**Issue by JoeMudd123** [lah7/sims2-4k-ui-patch#32]
Hello everyone,

Every time I try to run the script I get the following error:

https://i.imgur.com/2w4FvDA.png

It can output FontStyle.ini but not ui.package. What causes this error, and how can I fix it?

**Comment by lah7** [comment]
Sorry about that. The script hasn't been tested under Windows (ironically).

It seems that the `convert` command for Imagemagick did not run  [`Invalid Parameter`], but Windows apparently has a `convert` command for something else.  It is the script's fault for relying on an external command at the moment.

Before running the script, try setting the PATH environment variable to the Imagemagick folder first, which should pick up `convert` from [Imagemagick](https://imagemagick.org/script/download.php#windows) rather than Windows.

    setx path "c:\path\to\imagemagik;%path%"
    cd d:\sims2-4k-ui-mod-master\
    python3 ./sims2-4k-ui-converter.py 

If you have a Linux VM or WSL installed, it should definitely run under there instead. I'm currently working on a patcher program which will automate the entire process.

**Comment by lah7** [comment]
I've created a [v0.1.0 release](https://github.com/lah7/sims2-4k-ui-patch/releases/tag/v0.1.0). This new patcher program supersedes the old script and automates the process - all you need is your `EA GAMES` folder with The Sims 2 and its expansions.

In terms of [visual progress/bugs](https://github.com/lah7/sims2-4k-ui-patch/issues), it is relatively the same as last year. Still a work in progress!
