### ISSUE TITLE
Is it working? 

### ISSUE THREAD

**Issue by glorsh66** [lah7/sims2-4k-ui-patch#35]

**Comment by lah7** [comment]
Yes and no.

**Yes** - the theory works, but it's [tedious to do right now.](https://github.com/lah7/sims2-4k-ui-mod#script-usage)

**No** - I had been working on a patcher program, but other life things got in the way. I should pick it back up and get a first version out at some point. Watch this repository for releases! 🔔 

It's not perfect, there are [some bugs](https://github.com/lah7/sims2-4k-ui-mod/issues?q=is%3Aissue+is%3Aopen+label%3A%22visual+bug%22) that need further investigation. Hopefully, these can be addressed once this project becomes easy to patch/unpatch.

**Comment by NightFlutter** [comment]
where is the patcher exe? i only see sims2_4k_ui_patcher.py
sorry i don't understand python

**Comment by NightFlutter** [comment]
thanks and is it possible to make one for 1440p or 1080p? because i play on 1440p and this one makes the UI huge and also maybe it will fix some bugs if it's made for lower resolutions

**Comment by lah7** [comment]
1440p should be possible in future! For now, we'll focus on getting it right for 4K (200%, double density) and use what we learn from that to support other UI scales.

I've created a new issue so we can track demand → #37 → Be sure to give it a 👍🏼 !

Since you mentioned 1080p, I hadn't thought of fractional scaling, like zooming in 110% or 120%. It probably wouldn't look great since the UI is based on pixels, not vectors. Seems worthy of a future experiment - first, we'll need to see if the game's UI does supports decimal numbers or if it'll crash/corrupt the UI → #38
