### ISSUE TITLE
Patcher does not recognize game files in installation folder for Ultimate Collection

### ISSUE THREAD

**Issue by Etheziel** [lah7/sims2-4k-ui-patch#39]
### Operating System

Windows 11

### Patcher Program Version

v0.1.0

### Describe the problem

The patcher does not recognize my installation folder. I tried selecting it manually, that did not work either. It gives the error,

"Wrong folder selected
No installation of The Sims 2 (or its expansion packs) was found in this folder."

In the patcher status bar it says, "Missing EA Games Folder"

I tried to reinstall the game in the registry as "Program Files (x86)\EA GAMES\The Sims 2 Ultimate Collection\", but that did not work either. I also tried running as Administrator, and taking ownership of the folder and giving full control permissions. 

I am using The Sims 2 Starter Pack.

**Comment by lah7** [comment]
Thanks for the report. Can confirm the Ultimate Edition isn't recognised by the patcher at the moment since its file structure is different to the retail discs.

For example, it's expecting this:
```
'The Sims 2'                     'The Sims 2 Kitchen & Bath Interior Design Stuff'
'The Sims 2 Apartment Life'      'The Sims 2 Mansion and Garden Stuff'
'The Sims 2 Bon Voyage'          'The Sims 2 Nightlife'
'The Sims 2 Celebration! Stuff'  'The Sims 2 Open For Business'
'The Sims 2 Family Fun Stuff'    'The Sims 2 Pets'
'The Sims 2 FreeTime'            'The Sims 2 Seasons'
'The Sims 2 Glamour Life Stuff'  'The Sims 2 Teen Style Stuff'
'The Sims 2 H&M® Fashion Stuff'  'The Sims 2 University'
'The Sims 2 IKEA® Home Stuff'
```

With each folder more or less:
```
CSBin            eauninstall.ico  Sims2EP9.ico         Support  TSData
eauninstall.exe  filelist.txt     Sims2EP9_Uninst.exe  TSBin
```

It appears the Ultimate Edition lays out its files like this:
```
'Best of Business'  'Double Deluxe'  'Glamour Life Stuff'  'University Life'
'Bon Voyage'        'Fun with Pets'   Seasons
```

and then `TSData` can be found inside each of the subfolders:
```
EP3  SP5  SP7  VP6
```

I made a [modified build](https://github.com/lah7/sims2-4k-ui-patch/commit/ee6836e14df4754c5ec01dfda44ab01c66bea11e) that will see the Ultimate Collection. I'll need some time to fix it in the patcher properly. Till then, try this one:

[📁  sims2-4k-ui-patch-v0.1.0-ultimate-collection.zip](https://github.com/user-attachments/files/15833181/sims2-4k-ui-patch-v0.1.0-ultimate-collection.zip)

**Comment by Etheziel** [comment]
Great, it is recognizing it now and I patched and am checking it out in the game and I'm already loving the potential it is showing! Thanks for the great work.

**Comment by lah7** [comment]
Thanks for the compliment! Good news, the next release (v0.2.0) will properly support the Ultimate Collection.
