### ISSUE TITLE
[Question] Sims 2 on macOS

### ISSUE THREAD

**Issue by arthrfrts** [lah7/sims2-4k-ui-patch#41]
Would love to test this on macOS, but I'm having trouble to install my Ultimate Collection on it (both Origin and Starter Pack).

I followed [the steps in your archived repo](https://github.com/lah7/sims2-wine-patches/blob/master/README-D9VK.md) on it, but the game always shuts down after the EA splash screen. Do you know any updated instructions to install and run it?

I've tried both with Whisky and Gcenx' [Wineskin project](https://github.com/Gcenx/WineskinServer) already, but maybe I'm missing some wineskin?

Thanks for any help!

**Comment by lah7** [comment]
I haven't tried the EA App under Wine in a long time, and haven't babbled with Wine on Mac in over a decade. 🍷 

Since you say the game runs, but then crashes after the EA logo, some pointers could be:

- The in-game overlay is enabled and causes the crash. Try disabling it.
- EA/Origin's DRM (I believe is only supposed to run once) causes it?
- Maybe something to do with DXVK. 
   - I mean, if it wasn't present, stock Wine can't start the game and would crash with `D3DERR_INVALIDCALL!`

You might have luck using [Lutris](https://lutris.net/games/ea-app/) which _might_ use some other bundle of Wine. Looking at [their installer script](https://lutris.net/games/install/36644/view), they set up the wine prefix as "Windows 10" and installs `corefonts` too.

If you can, run with logging enabled or in a terminal, to see if any of the output provides a clue.

From what I can see, The Sims 2 Starter Pack doesn't require the EA App, so that 'version' would probably be easier to get up and running.

**Comment by arthrfrts** [comment]
Thanks for the pointers! I was actually trying to use Starter Pack, since the EA app would only bring more complexity to this.


I tried to configure Wineskin with WS12WineCX64Bit23.7.1-2, `d9vk`, `dxvk` and `corefonts`. This same bottle runs Spore flawlessly and, with some caveats, runs the SimCity 2013 on Origin. However, I believe The Sims 2 has something different, since it breaks after this:

```
[mvk-info] Created 3 swapchain images with initial size (1280, 720) and contents scale 1.0 for screen PHL 276E8V.
0254:trace:loaddll:build_module Loaded L"C:\\Program Files (x86)\\The Sims 2 Starter Pack\\Fun with Pets\\SP9\\TSBin\\ijl15.dll" at 60000000: native
info:  DXVK: Using 5 compiler threads
0254:fixme:imm:ImmGetOpenStatus (000300A4): semi-stub
2024-06-27 22:34:07.757 wine64-preloader[37025:1461433] [CAMetalLayerDrawable texture] should not be called after already presenting this drawable. Get a nextDrawable instead.
2024-06-27 22:34:07.757 wine64-preloader[37025:1461439] Each CAMetalLayerDrawable can only be presented once!
```

This _seems_ to be something that's missing from MoltenVK, I guess? Since `dxvk` goes through it to translate to Metal (if I'm understanding things correctly).


Anyway, it doesn't work for now, but maybe in the future since MoltenVK seems to be evolving. I'm playing it through Parallels (and is running flawlessly on a M1).

Thank you for your help!
